version: '2.3'
services:
  tensorflow-gpu-2:
    build: .
    volumes:
      - .:/user/src/app
      - /data:/data
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: /bin/bash
    tty: true
    stdin_open: true
    container_name: tensorflow-gpu-2
